language: node_js
os: 
  - linux
node_js:
  - latest # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
install:
  - npm install
script:
  - hexo generate # generate static files
after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: gh-pages
  # local_dir: public