language: node_js
os: 
  - linux
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
install:
  - npm install
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: public